### ISSUE TITLE
getAddressFromHex method parameter problem

### ISSUE THREAD

**Issue by woshidongyao** [StricaHQ/typhonjs#11]
How the hexAddress address is generated？

**Comment by ashisherc** [comment]
for generating address https://docs.strica.io/lib/typhonjs/classes/address.BaseAddress.html
for key derivation https://github.com/StricaHQ/bip32ed25519

also have a look at the tests for examples

**Comment by woshidongyao** [comment]
I checked the test case and its parameters are hardcoded

**Comment by ashisherc** [comment]
do have a look at the links above for generating your keys, and let me know what exactly is your doubts/question

**Comment by woshidongyao** [comment]
I have generated public and private keys and need to use public keys to generate addresses, but my public key is of type Uint8Array, I would like to know what type of parameter is the getAddressFromHex method

**Comment by ashisherc** [comment]
https://github.com/StricaHQ/bip32ed25519

**Comment by woshidongyao** [comment]
ok thanks

**Comment by ashisherc** [comment]
I will close this issue, please feel free to create another issue if you have any doubts regarding `typhonjs`

**Comment by woshidongyao** [comment]
Ok
