### ISSUE TITLE
How to serialise balance in typhonjs

### ISSUE THREAD

**Issue by judeebene** [StricaHQ/typhonjs#19]
Using cardano serilization lib , i get wallet balance  like 

`const getBalance = async () => {
  const balance = await window.cardano.selectedWallet.getBalance();
   const value = C.Value.from_bytes(fromHex(balance));
  const lovelace = parseInt(value.coin().to_str());
  return lovelace;
};`
I want to switching to typhonjs.
 what's the right way to get Value.from_bytes in TyphonJs or  a sample function to deserialise  wallet balance? @ashisherc

**Comment by ashisherc** [comment]
A new version of typhonjs is in works to make this seamless. Meanwhile you can do this for decoding the value CBOR returned by the dApp connectors,

```
const getMultiAsset = function (ma) {
  const tokens = [];
  if (_.isEmpty(ma)) {
    return tokens;
  }
  for (const [policyId, assets] of ma.entries()) {
    for (const [assetName, value] of assets.entries()) {
      tokens.push({
        policyId: policyId.toString("hex"),
        assetName: assetName.toString("hex"),
        amount: value.toString(),
      });
    }
  }
  return tokens;
};

const value = cbors.Decoder.decode(Buffer.from([wallet balance hex], 'hex'));

if (value instanceof Array) {
  ada = value[0].toString();
  tokens = getMultiAsset(value[1]);
} else {
  ada = value.toString();
}
```

You can refer to this CDDL for parsing any type of data from hex. Also, see cbors here, https://github.com/StricaHQ/cbors
