### ISSUE TITLE
Need to update calculateMinUtxoAmount() for Babbage era

### ISSUE THREAD

**Issue by inimrod** [StricaHQ/typhonjs#21]
Since the Vasil HF, per the [official docs](https://docs.cardano.org/cardano-testnet/about/testnet-introduction):

> the minUTxO formula is now calculated using original bytes instead of lovelacePerUTxOWord. For more details, see [CIP-55](https://cips.cardano.org/cips/cip55/).

As of typhonjs v1.2.7, the `calculateMinUtxoAmount()` in `utils` is still using the old formula. This now needs to be updated.

**Comment by mahnunchik** [comment]
Any news?

**Comment by ashisherc** [comment]
is this a road blocker somehow?

**Comment by mahnunchik** [comment]
It is not possible to send less then 1 ADA, currently the method `calculateMinUtxoAmount` calculates 0.999978 ADA. Even on https://typhonwallet.io/#/wallet

**Comment by inimrod** [comment]
> is this a road blocker somehow?

Not strictly, but the current workarounds are messy (at least for me 😄). I've got quite a few txs now that failed because the minUtxo is calculated incorrectly and ends up being lower than required, especially in cases where there's a lot of tokens in the bundle.

**Comment by ashisherc** [comment]
Noted, will update the lib shortly!

**Comment by ashisherc** [comment]
This update requires breaking changes. The lib will function fine by setting `lovelacePerUtxoWord` param to `34482`, hence will update this method along with the babbage era upgrades.

**Comment by ashisherc** [comment]
updated with https://github.com/StricaHQ/typhonjs/pull/34
