### ISSUE TITLE
Accept Number in protocol params and UTXOs

### ISSUE THREAD

**Issue by mahnunchik** [StricaHQ/typhonjs#28]
The idea behind is make library consumer to not depend on Bignumber.js itself. This may be done by accepting plain JS Numbers (or even strings) in protocol params values and UTXOs.

```js
BigNumber(BigNumber()) = BigNumber
BigNumber(Number) = BigNumber
BigNumber(String) = BigNumber
```

This can be implemented by wrapping any value in a `BigNumber` constructor inside a library.

Related:
* https://github.com/StricaHQ/typhonjs/pull/22

**Comment by ashisherc** [comment]
I'm releasing a new major version of the library with Babbage features, I have considered this suggestion and I feel that it is safer to use BigNumber to work with any Cardano token amount or ADA amount as they can be quite big. I have had got into situations where the number type does not work as expected. Specifically when someone is working with private/public testnets.

We will give it a thought again with Voltaire major release.
