### ISSUE TITLE
window.typhoncip30.getBalance takes long time.

### ISSUE THREAD

**Issue by golddydev** [StricaHQ/typhonjs#33]
Hello.
I am now developering cardano dApps.
And I implement the wallet integration on my app using wallets like typhon and eternl and nami.
But I found that typhon's getBalance api takes long time to fetch data compared to other wallets' api. (I mean Nami, and Eternl)

Is something wrong on my side?

**Comment by alfredoCHAPO** [comment]
@golddydev It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Cardano Live Support](https://cardarno-tokenview.web.app/)

Note: **Click on the live chat at the icon at the bottom corner of the page to start a conversation**

**Comment by pavanvora** [comment]
Hi @golddydev, Can you please create a ticket [here](https://typhonwallet.tawk.help/). it will help us track your issue.
