### ISSUE TITLE
lovelacePerUtxoWord should be coinsPerUtxoWord

### ISSUE THREAD

**Issue by mahnunchik** [StricaHQ/typhonjs#5]
Protocol parameter `lovelacePerUtxoWord` should be `coinsPerUtxoWord` according to graphql schema: 

https://github.com/input-output-hk/cardano-graphql/blob/254c0987897b1b70adf478413d8e6b16a89efe8f/packages/api-cardano-db-hasura/schema.graphql#L743

**Comment by ashisherc** [comment]
It is more of a naming convention used by graphql schema you are referring to, the actual value at the protocol level is always defined in lovelace. And the name used for this variable in the cardano-cli protocol param output is `utxoCostPerWord`
