### ISSUE TITLE
createPlutusDataCbor doesn't accept certain acceptable structures to cardano-cli

### ISSUE THREAD

**Issue by eselkin** [StricaHQ/typhonjs#8]
This structure is not accepted:
```
import { encode } from 'cborg';
import {utils} from "@strictahq/typhonjs"

const pkh = Buffer.from(await getPubKeyHash());
const pkhCBORed = Buffer.from(encode(pkh));

utils.createPlutusDataCbor({
  "fields": [
    {
      "fields": [ pkhCBORed ],
      "constructor": 0
    }
  ],
  "constructor": 0
}) 
```
or with the bytes tag and the CBOR as a string (as it is accepted in cardano-cli)

**Comment by ashisherc** [comment]
1. the encode import looks different, are you trying to use @stricahq/cbors?
2. pkh doesn't need to be cbor encoded (unless you are trying to do something specific)
3. I think you need to do Buffer.from(value, 'hex'), unless you know what the value is

**Comment by eselkin** [comment]
That was it. The data should just be the bytes of the PKH not CBOR encoded bytes. Hash comes out the same as cardano-cli with the CBOR string in JSON.
